<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], []],
    'longDescription' => [['id'], ['_controller' => 'App\\Controller\\ProductController::one'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
